Controllers/ActorsController.cs
using E_ticket.Data;
using E_ticket.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace E_ticket.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _actorsService;

        public ActorsController(IActorsService actorsService)
        {
            _actorsService = actorsService;
        }

        public async Task<IActionResult> Index()
        {
            var Actors = await _actorsService.GetAsync();

            return View(Actors);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create([Bind("ProfilePictureURL,FullName,Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            _actorsService.Add(actor);

            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Detail(int id)
        {
            var ActorDeatail = await _actorsService.GetByIdAsync(id);
            return View(ActorDeatail);
        }


        public async Task<IActionResult> Edit(int id)
        {
            var actor = await _actorsService.GetByIdAsync(id);
            return View(actor);
        }


        [HttpPost]
        public IActionResult Edit(Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            _actorsService.Update(actor);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            _actorsService.DeleteByIds(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/CinemaController.cs
using E_ticket.Data;
using E_ticket.Interface;
using E_ticket.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace E_ticket.Controllers
{
    public class CinemaController : Controller
    {
        private readonly ICinemaService _cinemaRepo;

        public CinemaController(ICinemaService cinemaRepository)
        {
            _cinemaRepo = cinemaRepository;
        }

        public async Task<IActionResult> Index()
        {
            var Actors = await _cinemaRepo.GetAsync();

            return View(Actors);
        }
        

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create([Bind("ProfilePictureURL,FullName,Bio")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            _cinemaRepo.Add(cinema);

            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Detail(int id)
        {
            var ActorDeatail = await _cinemaRepo.GetByIdAsync(id);
            return View(ActorDeatail);
        }


        public async Task<IActionResult> Edit(int id)
        {
            var actor = await _cinemaRepo.GetByIdAsync(id);
            return View(actor);
        }
        [HttpPost]
        public IActionResult Edit(Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            _cinemaRepo.Update(cinema);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            _cinemaRepo.DeleteByIds(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<JsonResult> Editt([FromQuery] int id)
        {
            var actor = await _cinemaRepo.GetByIdAsync(id);
            return Json(actor);
        }
    }
}

Controllers/MovieController.cs
using E_ticket.Interface;
using E_ticket.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;
namespace E_ticket.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _movieRepo;

        public MovieController(IMovieService movieService )
        {
            _movieRepo = movieService;
        }

        public async Task<IActionResult> Index()
        {
            var AllMovie = await _movieRepo.GetAllAsyncInclude();
            return View(AllMovie);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var movies = await _movieRepo.GetMovieBySearch(searchString);
            return View("Index", movies);
        }


        public async Task<IActionResult> Detail(int id)
        {
            var Movie = await _movieRepo.GetMovieByIdAsync(id);
            return View(Movie);
        }
        public async Task<IActionResult> Create()
        {
            var movieDropDownData = await _movieRepo.getDropDownMovie();

            ViewBag.CinemaId = new SelectList(movieDropDownData.cinemas, "Id", "Name");
            ViewBag.ProducerId = new SelectList(movieDropDownData.producers, "Id", "FullName");
            ViewBag.ActorId = new SelectList(movieDropDownData.Actors , "Id", "FullName");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewMovieVM newMovie)
        {
            if (!ModelState.IsValid)
            {
                var movieDropDownData = await _movieRepo.getDropDownMovie();

                ViewBag.CinemaId = new SelectList(movieDropDownData.cinemas, "Id", "Name");
                ViewBag.ProducerId = new SelectList(movieDropDownData.producers, "Id", "FullName");
                ViewBag.ActorId = new SelectList(movieDropDownData.Actors, "Id", "FullName");
                return View(newMovie);
            }
            await _movieRepo.addNewMovie(newMovie);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var movie = await _movieRepo.GetMovieByIdAsync(id);

            var movieDropDownData = await _movieRepo.getDropDownMovie();

            NewMovieVM MovieVM = new NewMovieVM
            {
                Id = movie.Id,
                StartDate = movie.StartDate,
                CinemaId = movie.CinemaId,
                Description = movie.Description,
                EndDate = movie.EndDate,
                ImageURL = movie.ImageURL,
                Name = movie.Name,
                Price = movie.Price,
                ProducerId = movie.ProducerId,
                ActorsIds = movie.movieActors.Select(a => a.ActorId).ToList(),
                MovieCategory= movie.MovieCategory,
            };

            ViewBag.CinemaId = new SelectList(movieDropDownData.cinemas, "Id", "Name");
            ViewBag.ProducerId = new SelectList(movieDropDownData.producers, "Id", "FullName");
            ViewBag.ActorId = new SelectList(movieDropDownData.Actors, "Id", "FullName");

            return View(MovieVM);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id,  NewMovieVM UpdatedMovie)
        {
            if (!ModelState.IsValid)
            {
                var movieDropDownData = await _movieRepo.getDropDownMovie();

                ViewBag.CinemaId = new SelectList(movieDropDownData.cinemas, "Id", "Name");
                ViewBag.ProducerId = new SelectList(movieDropDownData.producers, "Id", "FullName");
                ViewBag.ActorId = new SelectList(movieDropDownData.Actors, "Id", "FullName");
                return View(UpdatedMovie);
            }

            await _movieRepo.updateMovie(UpdatedMovie);
            return RedirectToAction(nameof(Index));
        }


    }
}

Controllers/OrdersController.cs
using E_ticket.Data.Cart;
using E_ticket.Data.ViewModel;
using E_ticket.Interface;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace E_ticket.Controllers
{
    public class OrdersController : Controller
    {
        private IMovieService _movieService { get; set; }
        private ShopingCart _shopingCart { get; set; }
        public IOrderService _orderService { get; set; }


        public OrdersController(IMovieService movieService, ShopingCart shopingCart, IOrderService orderService)
        {
            _movieService = movieService;
            _shopingCart = shopingCart;
            _orderService = orderService;
        }


        public IActionResult GetShopingCartItems()
        {
            var items = _shopingCart.GetShopingCartItems();
            _shopingCart.ShopingcartItems = items;

            var response = new ShopingCartVM
            {
                ShopingCart = _shopingCart,
                ShopingCartTotal = _shopingCart.GetShopingcartTotal(),
            };
            return View(response);
        }

        public async Task<ActionResult> Index()
        {
            string UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var UserRole = User.FindFirst(ClaimTypes.Role).Value;

            var orderlist = await _orderService.GetOrderByUserIdAndRoleAsync(UserId, UserRole);

            return View(orderlist);
        }

        public async Task<RedirectToActionResult> AddToShopingCart(int id)
        {
            var Item = await _movieService.GetMovieByIdAsync(id);
            if (Item != null)
            {
                _shopingCart.AdditemToCart(Item);
            }

            return RedirectToAction(nameof(GetShopingCartItems));
        }

        public async Task<RedirectToActionResult> Removeitemfromcart(int id)
        {
            var Item = await _movieService.GetMovieByIdAsync(id);
            if (Item != null)
            {
                _shopingCart.RemoveShopingCartItem(Item);
            }

            return RedirectToAction(nameof(GetShopingCartItems));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            string UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            string UserEmail = User.FindFirst(ClaimTypes.Email).Value;
            var Items = _shopingCart.GetShopingCartItems();
            await _orderService.StoreOrder(Items,UserId,UserEmail);
            await _shopingCart.ClearShopingcart();

            return View("OrderCompleted");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link href="https://fonts.cdnfonts.com/css/poppins" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Movie" asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index"><i class="bi bi-film"></i> Movies</a>
                        </li>

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Cinema" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                                    <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                    <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                                </div>
                            </li>
                        }
                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller="Movie" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShopingCartSummary")
                    </ul>
                    <partial name="_identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_identity.cshtml
@using Microsoft.AspNetCore.Identity;
@inject UserManager<ApplicationUser> usermanager;
@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success ml-2 my-sm-0" asp-controller="Account" asp-action="Login"> <i class="bi bi-box-arrow-in-right"></i> login </a>
    <a class="btn btn-outline-primary ml-2 my-sm-0" asp-controller="Account" asp-action="Register"> <i class="bi bi-person-plus"></i> Register </a>
}
else
{
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger ml-2 my-sm-0"> <i class="bi bi-box-arrow-in-right"></i> LogOut </button>
    </form>
    <div class="nav-item dropdown ml-2">
        <button class="nav-link dropdown-toggle btn btn-outline-success" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="bi bi-person-badge"></i>   Hello @usermanager.GetUserName(User)
        </button>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" asp-controller="Orders" asp-action="Index">orders</a>
        </div>
    </div>
}