Models/Producer.cs
using E_ticket.Data.Base;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;

namespace E_ticket.Models
{
    public class Producer : IEntityBase
    {
        public int Id { get; set; }

        [Display(Name = "ProfilePictureURL")]
        public string ProfilePictureURL { get; set; }

        [Display(Name = "FullName")]
        public string FullName { get; set; }

        [Display(Name = "Biography")]
        public string Bio { get; set; }

        public Collection<Movie> Moivies { get; set; }
    }
}

Controllers/ProducersController.cs
using E_ticket.Data;
using E_ticket.Interface;
using E_ticket.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace E_ticket.Controllers
{
    public class ProducersController : Controller
    {
       private readonly IProducerService _producerRepo;

        public ProducersController(IProducerService producerService )
        {
            _producerRepo = producerService;
        }

        public async Task<IActionResult> Index()
        {
            var Actors = await _producerRepo.GetAsync();

            return View(Actors);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create([Bind("ProfilePictureURL,FullName,Bio")] Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }
            _producerRepo.Add(producer);

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Detail(int id)
        {
            var ActorDeatail = await _producerRepo.GetByIdAsync(id);
            return View(ActorDeatail);
        }


        public async Task<IActionResult> Edit(int id)
        {
            var actor = await _producerRepo.GetByIdAsync(id);
            return View(actor);
        }
        [HttpPost]
        public IActionResult Edit(Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }
            _producerRepo.Update(producer);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            _producerRepo.DeleteByIds(id);
            return RedirectToAction(nameof(Index));
        }

       
    }
}

Views/Producers/Create.cshtml
@model Producer

@{ViewData["title"] = "Create New producer";}


<div style="width:700px;margin:auto;">
    <h2 class="text-center"> Add New Producer</h2> 
    <form asp-action="Create">
       <div class="form-group text-center">
           <img id="profile_pic_pre" style="border-radius:50%;">
       </div>
      <div class="form-group">
        <label for="Profile_Picture">Profile Picture</label>
        <input asp-for="ProfilePictureURL" type="text" class="form-control" id="Profile_Picture" >
        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label for="full_name">Full Name</label>
        <input asp-for="FullName" type="text" class="form-control" id="full_name">
         <span asp-validation-for="FullName" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label for="Biography">Biography</label>
        <input asp-for="Bio" type="text" class="form-control" id="Biography">
         <span asp-validation-for="Bio" class="text-danger"></span>
      </div>
      <div class="form-group">
         <button type="submit" class="btn btn-primary">Add</button>
         <button class="btn btn-secondary float-right" asp-action="Index">Show All</button>
      </div>
    </form>
</div>

@section scripts{
    <script>
        $("#Profile_Picture").on("change", function() {
           var output = document.getElementById("profile_pic_pre");
           output.src = $(this).val();
         
        })
    </script>
}

Views/Producers/Detail.cshtml
@model Producer

@{
    ViewData["title"] = "Details of producer";
}


<div style="width:700px;margin:auto;">
    <h2 class="text-center"> Detail of @Html.DisplayFor(m => m.FullName)</h2>
    <form>
        <div class="form-group text-center">
            <img id="profile_pic_pre" style="border-radius:50%;">
        </div>
        <div class="form-group">
            <label for="Profile_Picture">Profile Picture</label>
            <input asp-for="ProfilePictureURL" type="text" class="form-control" id="Profile_Picture" readonly>
        </div>
        <div class="form-group">
            <label for="full_name">Full Name</label>
            <input asp-for="FullName" type="text" class="form-control" id="full_name" readonly>
        </div>
        <div class="form-group">
            <label for="Biography">Biography</label>
            <input asp-for="Bio" type="text" class="form-control" id="Biography" readonly>
        </div>
        <div class="form-group">
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                <a asp-controller="Producers" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
            }
            <button class="btn btn-secondary float-right" asp-action="Index">Show All</button>
        </div>
    </form>
</div>

@section scripts{
<script>
    $( document ).ready(function() {
       var profile_pic = $("#Profile_Picture").val();
       var output = document.getElementById("profile_pic_pre");
       output.src = profile_pic;
    });
    $("#Profile_Picture").on("change", function() {
       var output = document.getElementById("profile_pic_pre");
       output.src = $(this).val();
    })
</script>
}

Views/Producers/Edit.cshtml
@model Producer

@{ViewData["title"] = "Update producer";}


<div style="width:700px;margin:auto;">
    <h2 class="text-center"> update producer</h2> 
    <form asp-action="Edit">
       <div class="form-group text-center">
           <img id="profile_pic_pre" style="border-radius:50%;">
       </div>
      <div class="form-group">
        <label for="Profile_Picture">Profile Picture</label>
        <input asp-for="ProfilePictureURL" type="text" class="form-control" id="Profile_Picture" >
        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label for="full_name">Full Name</label>
        <input asp-for="FullName" type="text" class="form-control" id="full_name">
         <span asp-validation-for="FullName" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label for="Biography">Biography</label>
        <input asp-for="Bio" type="text" class="form-control" id="Biography">
         <span asp-validation-for="Bio" class="text-danger"></span>
      </div>
      <div class="form-group">
         <button type="submit" class="btn btn-primary">Edit</button>
         <button class="btn btn-secondary float-right" asp-action="Index">Show All</button>
      </div>
    </form>
</div>

@section scripts{
    <script>
         $( document ).ready(function() {
           var profile_pic = $("#Profile_Picture").val();
           var output = document.getElementById("profile_pic_pre");
           output.src = profile_pic;  
        });
        $("#Profile_Picture").on("change", function() {
           var output = document.getElementById("profile_pic_pre");
           output.src = $(this).val();  
        })
    </script>
}

Views/Producers/Index.cshtml
@model IEnumerable<Producer>
@{
    ViewData["Title"] = "List of Producer";

}

<div class="row">
      <div class="col-md-8 offset-md-2">
           <table style="width:1000px">
               <thead>
                   <tr class="text-center">
                       <th> @Html.DisplayNameFor(model => model.ProfilePictureURL) </th>
                       <th> @Html.DisplayNameFor(model => model.FullName) </th>
                       <th> @Html.DisplayNameFor(model => model.Bio) </th>
                       <th> Actions </th>
                   </tr>
               </thead>
               <tbody>
                @foreach (var item in Model)
                {
                   <tr>
                     <td >
                        <img class="rounded-circle" src="@item.ProfilePictureURL" alt="@item.FullName" style="max-width:130px; margin:20px" >
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.Bio)
                    </td>
                      <td class="align-middle">
                            <a class="btn btn-outline-primary"   asp-action="Edit"   asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                            <a class="btn btn-outline-info"      asp-action="Detail" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete</a>
                        </td>
                   </tr>
                }
            </tbody>
           </table>
      </div>
</div>

<a asp-controller="Producers" asp-action="Create" class=" btn btn-success float-right  ">Add Producer</a>